---
- hosts: kube-cluster
  gather_facts: yes
  become: yes

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: cri-containerd, tags: cri-containerd }
    - { role: cni, tags: cni }

- hosts: node1
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }
    - { role: cri-containerd, tags: cri-containerd }

- hosts: node2
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }
    - { role: cri-containerd, tags: cri-containerd }

- hosts: master
  gather_facts: yes
  become: yes
  tasks:
    - name: "Helm role"
      include_role:
        name: helm
      when: "additional_features.helm"
      run_once: yes
      tags: helm

    - name: "MetalLB role"
      include_role:
        name: metallb
      when: "additional_features.metallb"
      run_once: yes
      tags: metallb

    - name: "Healthcheck role"
      include_role:
        name: healthcheck
      when: "additional_features.healthcheck"
      run_once: yes
      tags: healthcheck

