---
- name: "Install required packages on Ubuntu"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
      - unzip
      - tar
      - apt-transport-https
      - btrfs-tools
      - libseccomp2
      - util-linux

- name: "Get Containerd"
  unarchive:
    src: "https://storage.googleapis.com/cri-containerd-release/cri-containerd-{{ containerd_release_version }}.linux-amd64.tar.gz"
    dest: "/"
    remote_src: yes

- name: "Create a directory for cni binary"
  file: path={{ cni_bin_dir }} state=directory

- name: "Create a directory for cni config files"
  file: path={{ cni_conf_dir }} state=directory